### ISSUE TITLE
"Scenario" mod example not working

### ISSUE THREAD

**Issue by u-ndefine** [yairm210/Unciv-mod-example#7]
The scenario mod example is not working. When I try to start a new game with normal settings, it does not want to start. (v3.8.0)

**Comment by refola** [comment]
It starts for me, but crashes as soon as Writing is researched.

Specifically, "Next turn" always freezes if I have 1 turn left before discovering Writing. Sometimes it freezes a few turns sooner, presumably because the other civ happened to prioritize it and had more science. Sailing and Calendar are fine. I haven't tested other techs.

Playing around a bit, it also crashes when I build a Trireme. The Civ IV Scenario mod is very unstable :disappointed:. But at least the aliens mod works great!
